import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsSupport: SidebarsConfig = {
  supportSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebarsSupport;
